2022-03-16 06:00:47,343 ERROR: Exception on /search [GET] [in /home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kenneth/myrenamer/app/main/routes.py", line 148, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/kenneth/myrenamer/app/models.py", line 86, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/kenneth/myrenamer/app/search.py", line 19, in query_index
    search = current_app.elasticsearch.search(
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3696, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2022-03-16 06:00:54,966 ERROR: Exception on /search [GET] [in /home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kenneth/myrenamer/app/main/routes.py", line 148, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/kenneth/myrenamer/app/models.py", line 86, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/kenneth/myrenamer/app/search.py", line 19, in query_index
    search = current_app.elasticsearch.search(
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3696, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/kenneth/myrenamer/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
